### ISSUE TITLE
How to get user_id?

### ISSUE THREAD

**Issue by sectune** [antoinebou12/hass_renpho#16]
Title says it all, could not find user_id as the scale is used with multiple users. Thank you!

**Comment by antoinebou12** [comment]
https://hass-renpho.vercel.app/docs#/default/get_scale_users_users_get

login and then you can get the user id

but you don't need the user_id to use the app

**Comment by antoinebou12** [comment]
with the release v3.0.1 will help the user id is easy to find in the config flow
